### 登录游戏
POST localhost:8080/user/login
Content-Type: application/json

{
  "name": "a",
  "pass": "aaa"
}

###
POST localhost:8080/user/login
Content-Type: application/json

{
  "name": "b",
  "pass": "bbb"
}





### 加入新房间
POST localhost:8080/user/join_room
Content-Type: application/json

{
"name": "a",
"pass": "aaa"
}
###
POST localhost:8080/user/join_room
Content-Type: application/json

{
  "name": "b",
  "pass": "bbb"
}





### 进行下一步
POST localhost:8080/user/step_forward
Content-Type: application/json

{
  "name": "a",
  "pass": "aaa"
}
###
POST localhost:8080/user/step_forward
Content-Type: application/json

{
  "name": "b",
  "pass": "bbb"
}



###  登录状态  给前端使用
POST localhost:8080/user/login_status
Content-Type: application/json

{
  "name": "a",
  "pass": "aaa"
}
###
POST localhost:8080/user/login_status
Content-Type: application/json

{
  "name": "b",
  "pass": "bbb"
}